### PR TITLE
Allow displaying patch and minor versions

### LINKED ISSUE #45: Add a flag to include patch/minor dependency versions
Sometimes it is not possible to upgrade to latest (`semver` major may contain breaking changes).

So it is useful to see if any new patch/minor versions exist.

Thanks!

### PR DESCRIPTION
**Pull request by ozsay**
fixes #45

### CODE REVIEW

**Comment by mskelton** [comment]
So, I don't really like this approach to solving your issue as I don't want the plugin to be tied to the npm plugin in this way.  The benefit of using `suggestUtils` is that it can support multiple resolvers rather than just the npm registry.  It also keeps this plugin more closely aligned to the upgrade interactive plugin.

Another approach could be to use the range in the manifest as a second http call (worse than 1 call per package, but less bad than 3 calls per package.  This way, you would have two columns: "Satisfying" and "Latest" or something like. So, `package-a@^1.0.0` would have latest of 2.0.0 and satisfying of `1.1.0` and `package-b@~1.0.0` would have latest of 2.0.0 and satisfying of `1.0.1`.

**Comment by ozsay** [comment]
"Satisfying" and "Latest" is how it was implemented in yarn1 AFAIK

```
yarn outdated v1.22.5
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                                            Current    Wanted     Latest     Workspace                                          Package Type    URL
@babel/cli                                         7.16.0     7.16.0     7.17.6     ---                                                devDependencies https://babel.dev/docs/en/next/babel-cli
@babel/core                                        7.16.5     7.16.5     7.17.5     ---                                                devDependencies https://babel.dev/docs/en/next/babel-core
@babel/plugin-proposal-nullish-coalescing-operator 7.16.5     7.16.5     7.16.7     ---                                                devDependencies https://babel.dev/docs/en/next/babel-plugin-proposal-nullish-coalescing-operator
@babel/preset-env                                  7.16.5     7.16.5     7.16.11    ---                                                devDependencies https://babel.dev/docs/en/next/babel-preset-env
@babel/preset-typescript                           7.16.5     7.16.5     7.16.7     ---                                                devDependencies https://babel.dev/docs/en/next/babel-preset-typescript
@elastic/elasticsearch                             7.12.0     7.12.0     8.0.0      ---                                                dependencies    http://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/index.html
```

**Comment by mskelton** [comment]
Yeah, something like that would make more sense to me.

**Comment by mskelton** [comment]
Closing in favor of #64

**Pull request closed without merging**
